### ISSUE TITLE
Flickity results in significant Cumulative Layout Shift (CLS)

### ISSUE THREAD

**Issue by frankverhorst** [metafizzy/flickity#1087]
Perhaps unavoidably so, Flickity drags my site down with a significant Cumulative Layout Shift (CLS) score during Lighthouse and web.dev tests. Has anyone found a way around this?

**Comment by darkrubyist** [comment]
How did you solved it?

**Comment by codetot** [comment]
I think he doesn't found any solution yet.

Here is our result from Google PageSpeed.

<img width="389" alt="Screenshot_3" src="https://user-images.githubusercontent.com/68487935/95414514-4687a980-0958-11eb-9db6-fc1327c20977.png">

**Comment by MLDMoritz** [comment]
Problem is that flickity seems to remove the dom and then add it again, thus shifting the layout. Shouldn't be closed imho.

**Comment by BMarques** [comment]
I agree with MLDMoritz, this shouldn't be closed as it's causing CLS issues in our sites.

**Comment by desandro** [comment]
If layout shift is an issue for you, you can address it by manually setting your own carousel height by [disabling setGallerySize](https://flickity.metafizzy.co/options.html#setgallerysize)

```js
setGallerySize: false
```

``` css
/* carousel height */
.carousel {
  height: 160px;
}

/* cell inherit height from carousel */
.carousel-cell {
  height: 100%;
}
```
