### ISSUE TITLE
Wrong css class for styling page dots in docs

### ISSUE THREAD

**Issue by bnomei** [metafizzy/flickity#1224]
flickity v2.2

`.dot` is stated in docs but code uses `.flickity-page-dot`.

https://flickity.metafizzy.co/style.html#page-dots

```css
/* position dots in carousel */
.flickity-page-dots {
  bottom: 0px;
}
/* white circles */
.flickity-page-dots .dot {
  width: 12px;
  height: 12px;
  opacity: 1;
  background: transparent;
  border: 2px solid white;
}
/* fill-in selected dot */
.flickity-page-dots .dot.is-selected {
  background: white;
}
```
