### ISSUE TITLE
Misc CSS fixes

### ISSUE THREAD

**Issue by lunelson** [metafizzy/flickity#23]
I noticed that images have a few pixels of bottom-spacing due to being inline elements, and the navigation dots are susceptible to being selected; I threw in the following to the CSS, ymmv

```css
.flickity-enabled {
  position: relative;
  user-select: none; // ADDED
  img { display: block; } // ADDED
}
```
