### ISSUE TITLE
Avoid that page dots use multiple lines?

### ISSUE THREAD

**Issue by theo222** [metafizzy/flickity#309]
Hello 

How can I avoid that the page dots use multiple horizontal lines when there are a lot of items and/or small width?
Especially when dots are lines
http://codepen.io/desandro/pen/ByYyao
Can this work like a normal Scrollbar (percentual)?

Thank you!

**Comment by desandro** [comment]
Yes, you can use percents for dot size. See demo http://codepen.io/desandro/pen/9cc470785c642a4a602912fec98a1f7b/

**Comment by theo222** [comment]
Thank you, but this is not really what I mean, because it does not take the amount of items into account.
Even if you set .flickity-page-dots .dot width to 1%, there will be a new line for the 101st item, 
and if there are only a few items, the line is too short this way.

**Comment by desandro** [comment]
How about using flex box? See demo http://codepen.io/desandro/pen/9cc470785c642a4a602912fec98a1f7b/

``` css
.flickity-page-dots {
  display: flex;
}
/* dots are lines */
.flickity-page-dots .dot {
  flex-grow: 1;
}
```
