### ISSUE TITLE
Select cell on click

### ISSUE THREAD

**Issue by markseu** [metafizzy/flickity#342]
Hi, 

I would like to suggest a new [option](http://flickity.metafizzy.co/options.html) `clickable`. Enables clicking anywhere inside the Flickity div and [selects the next cell](http://flickity.metafizzy.co/api.html#next). For example if you create an image gallery: Visitors don't have to use arrow buttons, clicking would advance to the next image. What do you think about this idea?

**Comment by desandro** [comment]
Thanks for opening this issue. You can add this behavior with the [`cellSelect` event](http://flickity.metafizzy.co/api.html#staticclick). See demo  http://codepen.io/desandro/pen/VapRmV

``` js
$gallery.on( 'staticClick', function( event, pointer, cellElem, cellIndex ) {
  if ( cellIndex !== undefined ) {
    $gallery.flickity( 'select', cellIndex );
  }
});
```

**Comment by markseu** [comment]
How about adding a new option, so this becomes a configurable behavior? See demo http://fotorama.io/customize/arrows-click-swipe/

**Comment by desandro** [comment]
You can achieve that behavior [with previous & next button CSS](http://flickity.metafizzy.co/style.html#previous-next-buttons).  [See demo on CodePen](http://codepen.io/desandro/pen/f6c1b11bd9d096394d608374ff33c487)

``` css
/* arrow buttons cover entire carousel */
.flickity-prev-next-button {
  width: 50%;
  height: 100%;
  background: transparent;
}

.flickity-prev-next-button svg {
  width: 40px;
  height: 40px;
  top: 50%;
  transform: translateY(-50%);
}

.flickity-prev-next-button.previous svg {
  left: 10px;
  right: auto;
}

.flickity-prev-next-button.next svg {
  right: 10px;
  left: auto;
}
```
