### ISSUE TITLE
Padding on cell causes miscalculation of position

### ISSUE THREAD

**Issue by pavethiran** [metafizzy/flickity#35]
Using following css causes the bug:
```css
.gallery-cell {
    padding:0 8px;
}
```
This gets resolved if I resize the window.
