### ISSUE TITLE
Prev/Next Drop Shadow on SVG Path

### ISSUE THREAD

**Issue by raywongjr** [metafizzy/flickity#364]
Are there any methods/solutions/recommendations to adding a box shadow effect on the SVG arrows themselves (not the button element)? I believe using the css box-shadow will not work directly on the SVG path that's generated from the slider. Any ideas?

**Comment by mdmoreau** [comment]
You should be able to use the CSS drop-shadow filter (https://developer.mozilla.org/en-US/docs/Web/CSS/filter).  Its browser support is pretty good (http://caniuse.com/#feat=css-filters), and I think there's a polyfill out there for IE.

**Comment by desandro** [comment]
@mdmoreau Nice solution! here's a demo:

http://codepen.io/desandro/pen/7f0f99ead3ae8826e68c48aa81dc9bae

``` css
.flickity-prev-next-button svg {
  -webkit-filter: drop-shadow( 0px 3px 2px hsla(0, 0%, 0%, 0.5) );
  filter: drop-shadow( 0px 3px 2px hsla(0, 0%, 0%, 0.5) );
}
```
