### ISSUE TITLE
Resize Layout Problem

### ISSUE THREAD

**Issue by animaux** [metafizzy/flickity#399]
Not sure if this is an »adaptive height-problem« since I don’t have a fixed height. 

Resizing the window generally works fine, but the resize-logic seems to lag behind the final window width resulting in a broken layout. Resizing the window very slow seems to work. Reloading the page after resizing fixes the layout again.

Is there any obvious way to fix the layout on manual window resize I am missing? Or is it the above mentioned »adaptive height-problem«?

    imagesLoaded: true,
    contain: true

http://igb.ag.w014b07a.kasserver.com/referenzen/

(Sorry, wasn’t able to do a reduced test-case, hope this is not too complicated this way)

**Comment by desandro** [comment]
Looks like the delay is caused by the transitions on the images.

``` css
.flickity-slider li img {
  -webkit-transition: all 250ms ease-in;
  -moz-transition: all 250ms ease-in;
  transition: all 250ms ease-in;
}
```

Flickity needs to measure the images to properly layout the cells. If you're only using opacity and filter transitions, then I recommend setting only `filter` to transition.

``` css
.flickity-slider li img {
  -webkit-transition: -webkit-filter 250ms ease-in, opacity 250ms ease-in;
  -moz-transition: filter 250ms ease-in, opacity 250ms ease-in;
  transition: filter 250ms ease-in, opacity 250ms ease-in;
}
```
