### ISSUE TITLE
Microsft Edge, vertical touch scroll issue

### ISSUE THREAD

**Issue by mustafahlvc** [metafizzy/flickity#587]
Hi,
I ve tested with a windows 10 tablet, edge browser on the slider which is in flickity's demo page;
I cant touch and vertical scroll on the slider. The chrome works with no problem with the same tablet.

Thanks and I wish Microsoft won't make browsers anymore :|

**Comment by mustafahlvc** [comment]
The code below works as suggested in the issue #540 
```css
.flickity-viewport {
  touch-action: pan-y !important;
}
```
