### ISSUE TITLE
how to set groupCells at media queries 

### ISSUE THREAD

**Issue by yaodingyd** [metafizzy/flickity#592]
I saw the 'Set options at media queries' example at extra section but I don't see how to set groupCells dynamically. 

I understand the philosophy of flickity is keep CSS out of JS and use CSS, and media queries to style and make things responsive and I totally agree with this, but right now I'm stuck with how to set different `slidesToScroll` (pardon I use `slick` property).

Thank you very much for keep this project so well-maintained!

**Comment by yaodingyd** [comment]
One more question: is it possible to have arbitrary `slidesToScroll` with `groupCells`? Say I set `groupCells: 3`, but I want to scroll one slide each time. This is actually because I want arbitrary amount of  `is-selected` slides.

**Comment by desandro** [comment]
The solution you're looking for is to set the width of cells with your CSS

``` css
/* default/mobile, 2 cells in group */
.carousel-cell { width: 50%; }

@media ( min-width: 768px ) {
  /* tablet size, 3 cells in group */
  .carousel-cell { width: 33.33%; }
}

@media ( min-width: 1024px ) {
  /* desktop, 4 cells in group */
  .carousel-cell { width: 25%; }
}
```

See demo https://codepen.io/desandro/pen/JJaPwx


This works with [`groupCells: true`](https://flickity.metafizzy.co/options.html#groupcells), as Flickity will group cells that fit within 100% of the carousel width.
