### ISSUE TITLE
clicking on dots doesn't advance carousel

### ISSUE THREAD

**Issue by jarmstrong2** [metafizzy/flickity#624]
launched a site recently that uses flickity. for some reason clicking on the dots doesn't advance the carousel. http://www.cfmdc.org
thanks.

p.s. also tried to replicate a test case, but was not able to, so please check the site above

**Comment by yaodingyd** [comment]
@jarmstrong2  in your home.scss, line 293 

```scss
.dot {
  width: 8px;
  height: 8px;
  background: #000;
  position: relative;
  top: 16px;
}
```
Remove the last `top:16px;`.  If you want to position dots, apply style to `flickity-page-dots` directly. `dot` needs to be inside `flickity-page-dots` to work.
