### ISSUE TITLE
Viewport height persists

### ISSUE THREAD

**Issue by UisgeBeatha436** [metafizzy/flickity#704]
I'm trying to set the height of my header slider to 400px, however the class 'flickity-viewport' persists on 300px. Example can be found here https://www.uisge-beatha.eu/test-2

The html / smartyy code looks as follows:

``` html
<div class="main-carousel" data-flickity='{"imagesLoaded": true, "contain" : true, "percentPosition" : true, "initialIndex" : 2, "wrapAround" : true, "autoPlay": 2500, "setGallerySize": true, "adaptiveHeight": true}'>
{foreach from=$images item=image}
    <div class="carousel-cell"> 
        <div class="carousel-content">
            <div style="background: url({CGSmartImage src="{$image->file|escape:'url'|replace:'%2F':'/'}" noresponsive=1 alt="{$site_name} - {$image->title}" notag=1} ); no-repeat center center; height:400px; width:100%; background-size:cover;">
            </div>
        </div>
        <div class="carousel-meta">
             <h3>From Wetlands To Canals And Dams Amsterdam Is Alive</h3>
        <span><i class="fa fa-clock-o" aria-hidden="true"></i> January 7, 2013 </span>
   </div>
{/foreach}
</div>
```
According to the manual I tried chaning "setGallerySize" to false, but then the slider disappears.  

The CSS looks as follows:
``` css
.main-carousel .flickity-viewport {
  height: 400px;
}
.main-carousel {
  background: #AAA;
  padding: 1px;
  height: 100%;
}
 
.carousel-cell {
  position: relative;
  height: 100%;
  width: 100%;
  margin-right: 2px;
  background: #ddd;
}

.carousel-cell .carousel-content {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  height: 400px;
  -webkit-box-pack: center;
      -ms-flex-pack: center;
          justify-content: center;
  -webkit-box-align: end;
      -ms-flex-align: end;
          align-items: flex-end;
  color: white;
}
.carousel-cell .carousel-content .carousel-meta {
  background: -webkit-linear-gradient(top, transparent 0%, rgba(0, 0, 0, 0.9) 100%);
  background: linear-gradient(to bottom, transparent 0%, rgba(0, 0, 0, 0.9) 100%);
  padding: 120px 20px 40px 20px;
}
.carousel-cell .carousel-content h3 {
  color: white;
}
.flickity-viewport {
  height: 400px;
}
```

Been experimenting with chaning the "flickity-viewport", but no luck.

The images have a height of 400px., so the bottom 100px are not shown.

Is there a way to get the viewport to 400px?

One other thing I noticed is the "carousel-meta" is shown behind the photo's instead of in front. Is there a way to change this?

**Comment by desandro** [comment]
The height of the carousel is set by the height of the cells.

``` css
.carousel-cell {
  width: 28%;
  height: 200px;
  margin-right: 10px;
  background: #8c8;
  border-radius: 5px;
  counter-increment: carousel-cell;
}
```

Try changing `height: 200px;` to change the height of the carousel.
