### ISSUE TITLE
Change pagination dots to numbers?

### ISSUE THREAD

**Issue by elliottcoe** [metafizzy/flickity#800]
Couldn't find anything on google but, is there a way of changing the pagination dots into numbers?

**Comment by tonifisler** [comment]
You could do that with CSS:

```css
.flickity-page-dots {
	counter-reset: a;
}

.flickity-page-dots .dot::after {
	content: counter(a);
	counter-increment: a;
}
```
