### ISSUE TITLE
Hide slides other than the ones in view

### ISSUE THREAD

**Issue by smtrjpt** [metafizzy/flickity#877]
I have a slider with 3 items in view and groupCells: true.
I want the slides in view to be the only ones visible and the extra part to be hidden.
![ss](https://user-images.githubusercontent.com/28630185/49885783-20794700-fe5e-11e8-92fa-a7b51d954bca.png)
The circled black part is what i would like to be hidden from view of the user

**Comment by desandro** [comment]
Thanks for reporting this issue. You can control how many cells are displayed with CSS.

``` css
.carousel-cell {
  width: calc( (100% - 20px) /  3 );
  margin-right: 10px;
}
```

See demo https://codepen.io/desandro/pen/dd399b686bd41adf8f85af4bea501362/
