### ISSUE TITLE
Make keyboard navigation work when using prevNextButtons: false

### ISSUE THREAD

**Issue by ivancuric** [metafizzy/flickity#98]
When using `prevNextButtons: false` clicking them doesn't focus the slider, and the keys don't work.
You have to click the slider itself to give it focus in order to make them work.

When using `prevNextButtons: true` clicking the SVG buttons gives proper focus to the slider.

**Comment by desandro** [comment]
Thanks for reporting this bug. I'll look into it.

**Comment by ivancuric** [comment]
A potential problem, not sure if it has anything to do with it:
I put the buttons in a wrapper with `pointer-events: none`, while the buttons themselves had `pointer-events: all`.

**Comment by desandro** [comment]
With `prevNextButtons: false`, the buttons shouldn't even be on the page. How do you click them? Can you put together a test case for this?

**Comment by ivancuric** [comment]
I put in custom buttons of my own and put event handlers on them.
You can check it out on https://shoebedo.com/

**Comment by desandro** [comment]
Instead of creating custom buttons, I recommend adding CSS that moves the prev/next buttons to the top right corner.  See http://codepen.io/desandro/pen/LVVqBR


``` css
.flickity-prev-next-button {
  top: 10px;
  -webkit-transform: none;
      -ms-transform: none;
          transform: none;
}

.flickity-prev-next-button.previous {
  left: auto;
  right: 60px;
}

.flickity-prev-next-button.next {
  right: 10px;
}
```
